title: Marnix Suilen
description: #
logo: #


socials:
  Twitter: "#"
  Facebook: "#"
  Instagram: "#"
  GitHub: "#"
  Dribbble: "#"


scholar:

  last_name: [Suilen]
  first_name: [Marnix]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: references.bib
  # bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# Filter out certain bibtex entry keywords used internally from the bib output
filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website, preview]

# Maximum number of authors to be shown for each publication (more authors are visible on click)
max_author_limit:  # leave blank to always show all authors
more_authors_animation_delay: 10  # more authors are revealed on click using animation; smaller delay means faster animation
